use std::{
    env,
    fs::{self, File},
    io::Write,
    path::{Path, PathBuf},
};

// generated by `sqlx migrate build-script`
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    // Build scss files into a css bundle
    println!("cargo:rerun-if-changed=styles");
    let css: &str = grass::include!("styles/main.scss");
    let bundle_path = PathBuf::from(env::var("OUT_DIR")?).join("style.css");
    let mut bundle = File::create(bundle_path)?;
    bundle.write_all(css.as_bytes())?;

    Ok(())
}
